1 add github actions to make it possible to copy files to other repos (#2)
* Create copy-to-repo-youtube-api-data-transfer.yml

* Use different github action

Old github action might've been broken. I've used this one before and it worked.

* Need to specify repo owner

Update copy-to-repo-youtube-api-data-transfer.yml

* Create destination branch if it doesn't exist

Update copy-to-repo-youtube-api-data-transfer.yml

* Update checkout action

* Use forked github action that uses --force on push

For my use case I want to push files from one repo to another to a branch. I want the branch to always be the same and want the latest changes from the source repo. Currently if the branch exists and the action runs again it will fail.

error: failed to push some refs to REPO
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

* test

* Revert "test"

This reverts commit 14a64a5e57a60a187358ced27eb3d77315838019.

* Use rsync to copy folder contents not folder

* Combine steps to prevent commit overwrite

* test sending only .github

* Try specifying ci.yml file

* Test using nicer way to separate paths

Update copy-to-repo-youtube-api-data-transfer.yml

Update copy-to-repo-youtube-api-data-transfer.yml

* I think this make it use the latest version?

Update copy-to-repo-youtube-api-data-transfer.yml

* Better to use a specific release

Prevents accidental breaking

* Use fixed release

logic for --force flag was backwards

* Add flag to use --force

* Repo name changed

* I'm lazy, I'll just use latest

I manage both of these repos if something breaks it'll be because of me

* test github action

* Revert "test github action"

This reverts commit b89d0397b6c9fc9684a899b19a2deeb34168269f.

* Whitespace

* Reorder arguments

* Use new argument name

* Remove pointless github action step name

* Setup source files as env variable

* Update copy-to-repo-youtube-api-data-transfer.yml

* Add github action template

* I don't think I can use template github actions

* Update variable in template file

* Update README.md