Use forked github action that uses --force on push
For my use case I want to push files from one repo to another to a branch. I want the branch to always be the same and want the latest changes from the source repo. Currently if the branch exists and the action runs again it will fail.

error: failed to push some refs to REPO
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.